from collections.abc import Awaitable, Callable
from typing import Any, Protocol, TypeVar

from app.schemas.address import UserAddress
from app.schemas.product import Product
from app.schemas.shop import Shop


T = TypeVar("T")
Session = Any


class AuthRepositoryPort(Protocol):
    async def create_user(self, user_data: dict) -> None: ...
    async def find_by_username(self, username: str) -> dict | None: ...
    async def find_by_user_id(self, user_id: str) -> dict | None: ...


class AddressRepositoryPort(Protocol):
    async def run_in_transaction(self, callback: Callable[[Session], Awaitable[T]]) -> T: ...
    async def acquire_user_address_lock(self, *, user_id: str, session: Session) -> None: ...
    async def count_active(self, *, user_id: str, session: Session | None = None) -> int: ...
    async def create_address(self, address_data: dict, session: Session) -> Any: ...
    async def find_by_id(self, *, user_id: str, address_id: str, session: Session | None = None) -> UserAddress | None: ...
    async def list_active(self, user_id: str) -> list[UserAddress]: ...
    async def update_address(self, *, user_id: str, address_id: str, update_data: dict, session: Session) -> UserAddress | None: ...
    async def clear_default(self, *, user_id: str, update_time: Any, session: Session) -> None: ...
    async def set_default(self, *, user_id: str, address_id: str, update_time: Any, session: Session) -> bool: ...
    async def soft_delete(self, *, user_id: str, address_id: str, update_time: Any, session: Session) -> UserAddress | None: ...
    async def find_latest_active(self, *, user_id: str, session: Session) -> UserAddress | None: ...


class ShopRepositoryPort(Protocol):
    async def list_active(self, limit: int = 100) -> list[Shop]: ...
    async def find_by_shop_id(self, shop_id: str, session: Session | None = None) -> Shop | None: ...


class ProductRepositoryPort(Protocol):
    async def list_available_by_shop(self, shop_id: str, limit: int = 200) -> list[Product]: ...
    async def find_by_shop_and_food_ids(self, shop_id: str, food_ids: list[str], session: Session | None = None) -> list[Product]: ...
    async def reserve_stock(self, *, product: Product, quantity: int, session: Session) -> bool: ...


class OrderRepositoryPort(Protocol):
    async def run_in_transaction(self, callback: Callable[[Session], Awaitable[T]]) -> T: ...
    async def create_order(self, order_data: dict, session: Session | None = None) -> Any: ...
    async def find_by_idempotency_key(self, *, user_id: str, idempotency_key: str) -> dict | None: ...
    async def query_order_by_id(self, order_id: str, user_id: str) -> dict | None: ...
    async def query_order_status(self, order_id: str, user_id: str) -> dict | None: ...
    async def query_order_history(self, user_id: str) -> list[dict]: ...
    async def query_order_history_page(self, user_id: str, *, limit: int, cursor: str | None) -> tuple[list[dict], str | None]: ...
    async def cancel_order(self, order_id: str, user_id: str, expected_status: str, target_status: str) -> bool: ...


class ConversationRepositoryPort(Protocol):
    async def create_conversation(self, user_id: str, title: str) -> str: ...
    async def is_owned_by(self, conversation_id: str, user_id: str) -> bool: ...
    async def append_message(self, *, conversation_id: str, user_id: str, role: str, content: str) -> str | None: ...
    async def recent_messages(self, conversation_id: str, user_id: str, limit: int) -> list[dict]: ...
    async def list_conversations(self, user_id: str, *, limit: int, cursor: str | None) -> tuple[list[dict], str | None]: ...
    async def delete_conversation(self, conversation_id: str, user_id: str) -> bool: ...
